name: continuous-integration-and-delivery
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'

      - name: Cache node_modules folder
        id: cache-npm 
        uses: actions/cache@v2
        with:
          path: 'node_modules/*'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-modules-

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install
  
  test:
    runs-on: ubuntu-latest
    env:
      CHROME_BIN: google-chrome
    needs: [install]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.0'
      
      - name: Cache node_modules folder
        id: cache-npm 
        uses: actions/cache@v2
        with:
          path: 'node_modules/*'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-modules-

      - name: Run test
        run: npm run test:ci
    
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'production'
      BASE_HREF: '/angular-devops/'
    needs: [install]
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules folder
        id: cache-npm 
        uses: actions/cache@v2
        with:
          path: 'node_modules/*'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-modules-

      - name: Build 🔧
        run: npm run build:ci

      - name: Prepare dist 🔧
        run: |
          mkdir public 
          mv ./dist/angular-devops/* ./public/
          cp public/index.html public/404.html
      
      - name: Upload artifact ✈️
        uses: actions/upload-artifact@v2
        with:
          name: build-1
          path: public
  
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: public



      